### ISSUE TITLE
Alerts LineNumber in CSV file

### ISSUE THREAD

**Issue by Subharanjan2055** [mr-sherman/sarif-to-csv#6]
Hi, @mr-sherman 

Thank you for your respond on previous ticket,

I hope this email finds you well. I am writing to bring to your attention a query we have regarding the CSV reports generated by our system.

We have been using this action from 2022 and it has proven to be immensely beneficial for us. However, we have encountered a slight inconvenience regarding the visibility of line numbers alongside alerts in the CSV reports.

As you may know, the GitHub dashboard displays alerts based on line numbers, which assists us greatly in identifying and addressing vulnerabilities. However, the CSV reports currently do not include line numbers alongside alerts, causing some difficulty when sharing reports with clients.

Therefore, we kindly request if it would be possible to include line numbers with alerts in the source section of the CSV format. This adjustment would greatly enhance the usability of the reports and streamline our vulnerability management process.

Your assistance in this matter would be highly appreciated and would significantly contribute to the efficiency of our operations. If you require any further information or clarification regarding this request, please do not hesitate to contact us.

Thank you for your attention to this matter, and we look forward to your positive response.

Warm regards,
Subhranjan2055

**Comment by Subharanjan2055** [comment]
@mr-sherman 

Need these details in the output sarif files.
![image](https://github.com/mr-sherman/sarif-to-csv/assets/97287103/195524d6-7ae9-40cb-8648-a813840860ce)

**Comment by mr-sherman** [comment]
I added the line number, start colum, and end column.  Adding the end line isn't going to be useful unless I'm presenting the full data flow, which doesn't fit the CSV format very well.  

Descriptions / alert messages are going to have to be a separate work item - many of the descriptions  in the section of SARIF that I'm using to get many other items have commas and linebreaks, which will ruin the CSV format.  Need to think about how best to tackle that.  For now, however, you have line numbers you requested.
Thanks.

**Comment by Subharanjan2055** [comment]
Hi @mr-sherman ,

Thank you for your update, but however i have generated new report using v2.2 getting only empty column there is no line number showing for the particular alerts. Could you pls check there might be something missing or something else .

Thanks,
Subh

**Comment by Subharanjan2055** [comment]
@mr-sherman ,

Any update on this ?

**Comment by Subharanjan2055** [comment]
@mr-sherman gentle reminder !!!

Thanks,
Subh

**Comment by mr-sherman** [comment]
Checking - holiday weekend in the US.

**Comment by mr-sherman** [comment]
try v2.3

**Comment by Subharanjan2055** [comment]
Hi @mr-sherman ,

Using v2.3 getting blank column for the alerts number.

**Comment by mr-sherman** [comment]
For what field?  the start line, the start column, the end column, or all of them?

**Comment by mr-sherman** [comment]
Finally fixed - forgot to commit a file.  v2.4 should have all the results.  
From my test file:
```
NAME, SEVERITY, SCORE, TAGS, SOURCE, START LINE, START COLUMN, END COLUMN
Code injection,critical,9.3,["security" "external/cwe/cwe-094" "external/cwe/cwe-095" "external/cwe/cwe-079" "external/cwe/cwe-116"],app/routes/contributions.js,32,29,44
Code injection,critical,9.3,["security" "external/cwe/cwe-094" "external/cwe/cwe-095" "external/cwe/cwe-079" "external/cwe/cwe-116"],app/routes/contributions.js,33,31,48
Code injection,critical,9.3,["security" "external/cwe/cwe-094" "external/cwe/cwe-095" "external/cwe/cwe-079" "external/cwe/cwe-116"],app/routes/contributions.js,34,27,40
```
